# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

jobs:

- job: Test
  displayName: Test
  strategy:
    matrix:
      Python311:
        python.version: '3.11'
      Python312:
        python.version: '3.12'
      Python313:
        python.version: '3.13'
      Python314:
        python.version: '3.14'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
    displayName: 'Upgrade pip'
  - script: |
      pip install --index-url https://download.pytorch.org/whl/cpu torch
      pip install -e .[test] pytest-azurepipelines
      pytest -v -s \
        --cov=skkeras \
        --cov-branch \
        --cov-report=term-missing \
        --cov-report=xml \
        --cov-report=html \
        --junitxml=test-results.xml
    env:
      KERAS_BACKEND: torch
      PYTHONFAULTHANDLER: 1
    displayName: 'Run tests'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'htmlcov'
      artifact: 'coverage-html-$(python.version)'

- job: Coverage
  displayName: Coverage
  dependsOn: Test
  condition: succeeded()
  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      path: $(Pipeline.Workspace)
  - task: PublishCodeCoverageResults@2
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: '$(Pipeline.Workspace)/**/coverage.xml'
